package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Jan 16, 2023, 3:11:20 PM by Hibernate Tools 5.4.20.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
/**
 * Candidature generated by hbm2java
 */
@Entity
@Table(name="candidature"
    ,schema="public"
)

public class Candidature  implements java.io.Serializable {

    @Id @SequenceGenerator(name="Candidature_ID_GENERATOR", sequenceName="Candidature_ID_SEQ", allocationSize=1) @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="Candidature_ID_GENERATOR") private Integer id;

     private String nom;
     private String prenom;
     private Date datenaissance;
     private String adressepostale;
     private String adresseemail;
     private Boolean cv;
     private Date datedepot;
     private Set<Secteuractivite> secteuractivites = new HashSet<Secteuractivite>(0);
     private Set<Messageoffreemploi> messageoffreemplois = new HashSet<Messageoffreemploi>(0);
     private Set<Messagecandidature> messagecandidatures = new HashSet<Messagecandidature>(0);

    public Candidature() {
    }

	
    public Candidature(int id, String nom, String prenom, String adressepostale, String adresseemail) {
        this.id = id;
        this.nom = nom;
        this.prenom = prenom;
        this.adressepostale = adressepostale;
        this.adresseemail = adresseemail;
    }
    public Candidature(int id, String nom, String prenom, Date datenaissance, String adressepostale, String adresseemail, Boolean cv, Date datedepot, Set<Secteuractivite> secteuractivites, Set<Messageoffreemploi> messageoffreemplois, Set<Messagecandidature> messagecandidatures) {
       this.id = id;
       this.nom = nom;
       this.prenom = prenom;
       this.datenaissance = datenaissance;
       this.adressepostale = adressepostale;
       this.adresseemail = adresseemail;
       this.cv = cv;
       this.datedepot = datedepot;
       this.secteuractivites = secteuractivites;
       this.messageoffreemplois = messageoffreemplois;
       this.messagecandidatures = messagecandidatures;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nom", nullable=false, length=50)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="prenom", nullable=false, length=50)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datenaissance", length=13)
    public Date getDatenaissance() {
        return this.datenaissance;
    }
    
    public void setDatenaissance(Date datenaissance) {
        this.datenaissance = datenaissance;
    }

    
    @Column(name="adressepostale", nullable=false, length=50)
    public String getAdressepostale() {
        return this.adressepostale;
    }
    
    public void setAdressepostale(String adressepostale) {
        this.adressepostale = adressepostale;
    }

    
    @Column(name="adresseemail", nullable=false, length=50)
    public String getAdresseemail() {
        return this.adresseemail;
    }
    
    public void setAdresseemail(String adresseemail) {
        this.adresseemail = adresseemail;
    }

    
    @Column(name="cv")
    public Boolean getCv() {
        return this.cv;
    }
    
    public void setCv(Boolean cv) {
        this.cv = cv;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datedepot", length=13)
    public Date getDatedepot() {
        return this.datedepot;
    }
    
    public void setDatedepot(Date datedepot) {
        this.datedepot = datedepot;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="index_candidature_secteuractivite", schema="public", joinColumns = { 
        @JoinColumn(name="idcandidature", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idsecteur", nullable=false, updatable=false) })
    public Set<Secteuractivite> getSecteuractivites() {
        return this.secteuractivites;
    }
    
    public void setSecteuractivites(Set<Secteuractivite> secteuractivites) {
        this.secteuractivites = secteuractivites;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidature")
    public Set<Messageoffreemploi> getMessageoffreemplois() {
        return this.messageoffreemplois;
    }
    
    public void setMessageoffreemplois(Set<Messageoffreemploi> messageoffreemplois) {
        this.messageoffreemplois = messageoffreemplois;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidature")
    public Set<Messagecandidature> getMessagecandidatures() {
        return this.messagecandidatures;
    }
    
    public void setMessagecandidatures(Set<Messagecandidature> messagecandidatures) {
        this.messagecandidatures = messagecandidatures;
    }




}


