package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Jan 16, 2023, 3:11:20 PM by Hibernate Tools 5.4.20.Final


import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
/**
 * Messagecandidature generated by hbm2java
 */
@Entity
@Table(name="messagecandidature"
    ,schema="public"
)

public class Messagecandidature  implements java.io.Serializable {


@Id @SequenceGenerator(name="MessageCandidature_ID_GENERATOR", sequenceName="MessageCandidature_ID_SEQ", allocationSize=1) @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="MessageCandidature_ID_GENERATOR") private Integer id;
     private Candidature candidature;
     private Offreemploi offreemploi;
     private Date dateenvoi;
     private String corpsMessage;

    public Messagecandidature() {
    }

	
    public Messagecandidature(int id) {
        this.id = id;
    }
    public Messagecandidature(int id, Candidature candidature, Offreemploi offreemploi, Date dateenvoi, String corpsMessage) {
       this.id = id;
       this.candidature = candidature;
       this.offreemploi = offreemploi;
       this.dateenvoi = dateenvoi;
       this.corpsMessage = corpsMessage;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_candidature")
    public Candidature getCandidature() {
        return this.candidature;
    }
    
    public void setCandidature(Candidature candidature) {
        this.candidature = candidature;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_offre")
    public Offreemploi getOffreemploi() {
        return this.offreemploi;
    }
    
    public void setOffreemploi(Offreemploi offreemploi) {
        this.offreemploi = offreemploi;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateenvoi", length=13)
    public Date getDateenvoi() {
        return this.dateenvoi;
    }
    
    public void setDateenvoi(Date dateenvoi) {
        this.dateenvoi = dateenvoi;
    }

    
    @Column(name="corps_message")
    public String getCorpsMessage() {
        return this.corpsMessage;
    }
    
    public void setCorpsMessage(String corpsMessage) {
        this.corpsMessage = corpsMessage;
    }




}


