package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Jan 16, 2023, 3:11:20 PM by Hibernate Tools 5.4.20.Final


import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
/**
 * Niveauqualification generated by hbm2java
 */
@Entity
@Table(name="niveauqualification"
    ,schema="public"
)

public class Niveauqualification  implements java.io.Serializable {


@Id @SequenceGenerator(name="niveauqualification_ID_GENERATOR", sequenceName="niveauqualification_ID_SEQ", allocationSize=1) @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="niveauqualificationID_GENERATOR") private Integer id;
     private String intitule;
     private Set<Offreemploi> offreemplois = new HashSet<Offreemploi>(0);

    public Niveauqualification() {
    }

	
    public Niveauqualification(int id, String intitule) {
        this.id = id;
        this.intitule = intitule;
    }
    public Niveauqualification(int id, String intitule, Set<Offreemploi> offreemplois) {
       this.id = id;
       this.intitule = intitule;
       this.offreemplois = offreemplois;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="intitule", nullable=false, length=50)
    public String getIntitule() {
        return this.intitule;
    }
    
    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="niveauqualification")
    public Set<Offreemploi> getOffreemplois() {
        return this.offreemplois;
    }
    
    public void setOffreemplois(Set<Offreemploi> offreemplois) {
        this.offreemplois = offreemplois;
    }




}


