package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Jan 16, 2023, 3:11:20 PM by Hibernate Tools 5.4.20.Final


import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
/**
 * Secteuractivite generated by hbm2java
 */
@Entity
@Table(name="secteuractivite"
    ,schema="public"
)

public class Secteuractivite  implements java.io.Serializable {

@Id @SequenceGenerator(name="secteuractivite_ID_GENERATOR", sequenceName="secteuractivite_ID_SEQ", allocationSize=1) @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="secteuractivite_ID_GENERATOR") private Integer id;
     private String intitule;
     private Set<Candidature> candidatures = new HashSet<Candidature>(0);
     private Set<Offreemploi> offreemplois = new HashSet<Offreemploi>(0);

    public Secteuractivite() {
    }

	
    public Secteuractivite(int id, String intitule) {
        this.id = id;
        this.intitule = intitule;
    }
    public Secteuractivite(int id, String intitule, Set<Candidature> candidatures, Set<Offreemploi> offreemplois) {
       this.id = id;
       this.intitule = intitule;
       this.candidatures = candidatures;
       this.offreemplois = offreemplois;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="intitule", nullable=false, length=100)
    public String getIntitule() {
        return this.intitule;
    }
    
    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="index_candidature_secteuractivite", schema="public", joinColumns = { 
        @JoinColumn(name="idsecteur", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idcandidature", nullable=false, updatable=false) })
    public Set<Candidature> getCandidatures() {
        return this.candidatures;
    }
    
    public void setCandidatures(Set<Candidature> candidatures) {
        this.candidatures = candidatures;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="index_secteuractivite", schema="public", joinColumns = { 
        @JoinColumn(name="idsecteur", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idoffre", nullable=false, updatable=false) })
    public Set<Offreemploi> getOffreemplois() {
        return this.offreemplois;
    }
    
    public void setOffreemplois(Set<Offreemploi> offreemplois) {
        this.offreemplois = offreemplois;
    }




}


